// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  CALLIGRAPHY_1: "https://images.unsplash.com/photo-1582033131298-5bb54c589518?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw4fHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_2: "https://images.unsplash.com/photo-1542618027-13d3eb1b438e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwzfHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_3: "https://images.unsplash.com/photo-1579410554773-df7ff7f3faaa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw0fHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_4: "https://images.unsplash.com/photo-1653573900958-5108e93aa15a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw1fHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_5: "https://images.unsplash.com/photo-1655579263938-f76495c680df?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwxfHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_6: "https://images.unsplash.com/photo-1655122350472-5ffc49e8f550?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw3fHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_7: "https://images.unsplash.com/photo-1661961905776-e131907b3fa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHwyfHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  CALLIGRAPHY_8: "https://images.unsplash.com/photo-1628405633956-385f623b767d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4Mzc5NTV8MHwxfHNlYXJjaHw2fHx0cmFkaXRpb25hbCUyMGlzbGFtaWMlMjBjYWxsaWdyYXBoeXxlbnwwfDB8fGdyZWVufDE3NzE4NTk5NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_1: "https://images.unsplash.com/photo-1575863591437-58b22055bdca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw3fHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_2: "https://images.unsplash.com/photo-1732203971761-e9d4a6f5e93f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw0fHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_3: "https://images.unsplash.com/photo-1631006732121-a6da2f4864d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw2fHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_4: "https://images.unsplash.com/photo-1761141535933-7f8e9f468865?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw1fHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_5: "https://images.unsplash.com/photo-1736134869040-1c1853bc23cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw4fHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_6: "https://images.unsplash.com/photo-1761593280919-766a4acbcfca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_7: "https://images.unsplash.com/photo-1771227241320-8fc5388259c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
  DASHBOARD_UI_8: "https://images.unsplash.com/photo-1759256243611-502772ac391b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwzfHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MHwwfHx8MTc3MTg1NjYwN3ww&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
